### ISSUE TITLE
Will this only work on values?

### ISSUE THREAD

**Issue by corysimmons** [andyjansson/postcss-functions#12]
Or can you use functions as properties, selectors, etc. (pretty much anywhere)?

**Comment by andyjansson** [comment]
It currently works on declarations and `@`-rules.

**Comment by corysimmons** [comment]
So properties or values in the declaration? And no selectors?

**Comment by andyjansson** [comment]
[Declarations](https://github.com/andyjansson/postcss-functions/blob/master/test/test.js#L14) and [`@`-rules](https://github.com/andyjansson/postcss-functions/blob/master/test/test.js#L61).

Any reason why you'd want to execute a function within a selector?

**Comment by corysimmons** [comment]
`a: b;` is a declaration. `a` is the property. `b` is the value. https://developer.mozilla.org/en-US/docs/Web/CSS/Syntax

Your examples all show the function only being used as a value, not an entire declaration.

TBH I haven't thought of anything to do with this yet, but it seems pretty awesome and if I know if can do XYZ, I can think of different ways to implement it. :)

**Comment by andyjansson** [comment]
Correct, you can only evaluate functions within the value of a declaration, and within the parameters of an `@`-rule.

**Comment by corysimmons** [comment]
Okay gotcha. Thanks. :+1:
