### ISSUE TITLE
Can this work with preprocessors?

### ISSUE THREAD

**Issue by corysimmons** [andyjansson/postcss-functions#13]
I'm pretty sure Stylus would have a meltdown if it came across `color: foobar();`

Is there a workaround for working with preprocessors AND postcss-functions? Does it work with PostCSS parsers like https://github.com/postcss/postcss-scss by chance??

**Comment by andyjansson** [comment]
I don't see why it wouldn't work with postcss-scss. All postcss plugins work by transforming an AST. That AST should be the same regardless of what parser is used.

**Comment by corysimmons** [comment]
I'll leave this open til I have some time to try it out.
