### ISSUE TITLE
Can not access a map's value via string key.

### ISSUE THREAD

**Issue by haohcraft** [andyjansson/postcss-functions#15]
I have a color function:

```
const COLORS = {
 blue: "#12121",
 orange: "#121212"
};

export default = {
 'fnc-color': (key) => COLORS[key]
};
```

Strange thing happens that when calling:

```
color: fnc-color(blue)
```

it works, but it will return `undefined` when below

```
color: fnc-color('blue')
```

So is there any difference when `postcss` or `postcss-functions` interpret `blue` and `"blue"`?

**Comment by andyjansson** [comment]
Ping @TrySound

**Comment by TrySound** [comment]
@andyjansson The only separator in arguments is comma, everything between them are stringified. You can go deeper and validate values by checking commas around strings or spaces between words.

**Comment by andyjansson** [comment]
Looking at the documentation for postcss-value-parser, it looks like we could just read from the `value` property whenever we encounter a `string` node. 

The question is, should we? Should `blue` and `"blue"` be treated as equivalent?

/cc @ben-eb @jonathantneal @ai care to weigh in?

**Comment by ben-eb** [comment]
My view is that they are not equivalent. For example, in the `grid-template-areas` property, we must define either `none` or one or more `<string>` values. Semantically in this case, `none` is "no grid template area" and `"none"` is a grid with one area named `none`.

https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-areas

**Comment by andyjansson** [comment]
@ben-eb You make a compelling argument to not change the current behaviour of the plugin.

@haohcraft I'm afraid you're going to have to strip out the quotes manually inside your function. Here's an example of how to do it: http://stackoverflow.com/questions/2608665/how-can-i-trim-beginning-and-ending-double-quotes-from-a-string/2608682#2608682

**Comment by haohcraft** [comment]
Thanks to all !
