### ISSUE TITLE
String into Int returns NaN?

### ISSUE THREAD

**Issue by drolsen** [andyjansson/postcss-functions#17]
Unable to convert a string to int and return it.
```
var options = {
    functions: {
        parseInt: function (value) {
		return parseInt(value);
        }
    }
};
```
```
.selector {
	XXXX: parseInt("12");
}
```
returns NaN in my sheet?

**Comment by andyjansson** [comment]
Hello. Sorry for the late reply, I've been away over the weekend. 
Have you tried passing in the value without the quotes?

**Comment by drolsen** [comment]
Yes giving a number to the function gives me a number back, but the purpose of this function will be to turn strings and floats into whole numbers for further functionality needs in my sheets. Are we locked into using a single data type for passing and returning?

**Comment by andyjansson** [comment]
A CSS [declaration's value](http://api.postcss.org/Declaration.html#value) is always going to be a string. When you call `parseInt("12")`, that will be the equivalent of doing `parseInt("\"12\"")` in JavaScript. Whenever you read a value from the declaration, it will be as a string, and whenever you return a value back to the declaration, it will be stringified to be inserted back into the declaration's value string.
