### ISSUE TITLE
Access to CSS property

### ISSUE THREAD

**Issue by danielpeplow** [andyjansson/postcss-functions#18]
It would be great if there was a way of getting access to the CSS property that the value (function) e.g:

```
.foo {
    color: darken(#fff, 10%);
}
```

Where darken would give you access to 'color' as a string.

The use case for this is that I wish to be able to pass some of the arguments of the function (including the property) to JavaScript

**Comment by andyjansson** [comment]
This could be tricky. The plugin was never developed with intent to provide access to the declaration, only the function part itself. 

At one hand, I'd like to help you, but at the other, I wouldn't want to break the plugin for people already using it, and this functionality could be considered out of scope. 

I'd like to hear more from the community about this.

**Comment by AlexWayfer** [comment]
> Where darken would give you access to 'color' as a string.

It's a code repetition, but I see an option to write `color: darken('color', #fff, 10%)`.
