### ISSUE TITLE
can not handle Variables defined with in context

### ISSUE THREAD

**Issue by changfuguo** [andyjansson/postcss-functions#19]
> here i defined a variable in setting.css
> use just like below

```
:root { 
	--baseGap: 10;
}

```

> the code below can work well 

```

width: rem(750);

```

> but the code below can not work 

```
width:rem(var(--baseGap))

```

the param is var(--baseGap)? how can solve it ,and change var(--baseGap) to real value ?

**Comment by andyjansson** [comment]
Change your plugin order so that postcss-css-variables executes before postcss-functions.

**Comment by afcsantos** [comment]
how can I setup postcss-css-variables on nuxt.js
