### ISSUE TITLE
Use functions in selectors

### ISSUE THREAD

**Issue by PaulKiddle** [andyjansson/postcss-functions#21]
I'd really like to be able to call a functions as part of a selector, something like this:

```javascript
li:nth-child(getNextChild()) {
  // etc
}
```

Is this feasable?

**Comment by andyjansson** [comment]
Unfortunately, selectors aren't currently supported. I could update the package and extend it with this functionality, however it's gonna be a few weeks before I can get started on anything like that.

**Comment by PaulKiddle** [comment]
Thanks. If I get a chance I'll try and look into creating a PR for it.

**Comment by andyjansson** [comment]
@NeonPaul I've implemented functions as part of selectors in the new beta. You're welcome to try it: 

```
npm i postcss-functions@next
```

**Comment by andyjansson** [comment]
v3.0.0 published. You can download it now by running `npm i postcss-functions`.
