### ISSUE TITLE
Upgrade to PostCSS v6

### ISSUE THREAD

**Issue by retyui** [andyjansson/postcss-functions#22]
Please Upgrade PostCSS dependency to v6  :)
CHANGELOG: https://github.com/postcss/postcss/blob/master/CHANGELOG.md

**Comment by andyjansson** [comment]
I'm in the process of rewriting the library in es6. With that release, the dependencies will be lifted as well.

**Comment by retyui** [comment]
@andyjansson Thank you 👍 , we are waiting for the release

**Comment by borodean** [comment]
Thanks for finishing it up, @andyjansson! Looks great.

**Comment by andyjansson** [comment]
@borodean Thanks!
