### ISSUE TITLE
How to get declaration object ?

### ISSUE THREAD

**Issue by retyui** [andyjansson/postcss-functions#23]
https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md#3-errors
How i can use this metod to send warn / error?

**Comment by retyui** [comment]
up

**Comment by andyjansson** [comment]
I'm afraid I don't have an answer for you. You currently don't have access to the declaration itself, and I'm wary of changing it. Could you perhaps throw errors and use `console.warn()` instead?
