### ISSUE TITLE
Fix example

### ISSUE THREAD

**Issue by Mexflubber** [andyjansson/postcss-functions#28]
Hi,

In the example on the Readme you state how to call the function foobar()

    body {
	    prop: foobar();
    }

But how do you define foobar() in css? I'm looking for a replacement of sass @function

**Comment by andyjansson** [comment]
There's nothing to fix. The project is specifically about exposing *JavaScript* functions; both the readme and project description reflects that. Replicating Sass has never been part of the project's goals, and defining functions in CSS is a bit out of scope. 

My recommendation (and that of @ai, PostCSS' creator) is to avoid putting too much logic into the stylesheet. Failing that, if you specifically need sass-like functionality, why not stick with sass?

**Comment by Mexflubber** [comment]
Well, in your readme you call "foobar" but you never declare it. Would you mind explaining how ?

I'm trying to bump my project to postcss. If I need to refactor my project to remove the logic from the css It's fine. Right now I'm just trying to understand how your plugin works. Please explain how to define "foobar".

**Comment by andyjansson** [comment]
It's literally in the documentation: https://github.com/andyjansson/postcss-functions#options 

You can also check the tests: https://github.com/andyjansson/postcss-functions/tree/master/src/__tests__
