### ISSUE TITLE
Critical dependency for plugins in webpack

### ISSUE THREAD

**Issue by pavelthq** [andyjansson/postcss-functions#29]
Related to https://github.com/postcss/postcss/issues/1139
webpack cannot build this due to it is critical dependency that cannot be solved in build-time
options.glob:
```
functions[name] = require(file);
```

After removing these code webpack is working correctly.

**Comment by pavelthq** [comment]
@andyjansson what is the point to close the issue is it resolved?

**Comment by andyjansson** [comment]
Yes, the issue is resolved. The `glob` feature has been dropped altogether, and it's now up to the user to decide how to include their scripts.
