### ISSUE TITLE
How to use with postcss.config.js? 

### ISSUE THREAD

**Issue by cmoeser** [andyjansson/postcss-functions#30]
How to use with postcss.config.js? Tried several variations like this but no luck.

const path = require('path');

module.exports = {
  "plugins": {
    "postcss-import": {},
    "postcss-apply": {},
    "postcss-preset-env": {},
    "postcss-functions": {  option: { functions: { glob: path.join(__dirname, '/assets/css/functions', '*.js')} }  },
    "postcss-mixins": {},
    "postcss-nested": {},
    "postcss-custom-media": {},
    "postcss-media-minmax": {},
    "postcss-discard-comments": {},
    "postcss-clean": {}  
    },
    "preset" : {
      "autoprefixer": {
       "grid": true
      }
    }
}

**Comment by andyjansson** [comment]
Try this: 

```
 "postcss-functions": { functions: { glob: path.join(__dirname, '/assets/css/functions', '*.js')} },
```

**Comment by cmoeser** [comment]
Thanks for the prompt response! Tried, no luck. Doesn't seem to load the functions.js at all. No error.

**Comment by andyjansson** [comment]
Oh whoops, a mistake on my part. It should be:

```
 "postcss-functions": { glob: path.join(__dirname, '/assets/css/functions', '*.js') },
```

Note that `glob` is used to scan a directory and automatically load the scripts contained in that directory. If you want to explicitly load a script, you should use the `functions` option, like so:

```
const myScript = require('./path/to/script');

...
 "postcss-functions": { functions: { myScript: myScript } }
...
```
