### ISSUE TITLE
Alpha value disappears in the only example

### ISSUE THREAD

**Issue by Wmaileq** [andyjansson/postcss-functions#33]
![image](https://user-images.githubusercontent.com/26236198/53881035-ab17af80-4023-11e9-9472-8f83d0d0d562.png)

function lost alpha value of initial color
https://github.com/andyjansson/postcss-functions/pull/32

**Comment by andyjansson** [comment]
It's just an example to demonstrate the functionality of the plugin. It really doesn't matter.
