### ISSUE TITLE
options.glob fail to work

### ISSUE THREAD

**Issue by dtvn** [andyjansson/postcss-functions#35]
This is the error it returns:
> Loading PostCSS Plugin failed: Cannot find module './style/fn/xx.js'

My `.postcssrc.js` file
```Js
module.exports = {
	parser: 'sugarss',
	plugins: {
		// ...
		'postcss-functions': {
			glob: './style/fn/*.js'
		},
		// ...
	}
}
```

I have a `xx.js` in `style/fn` dir. However it didn't work like in the guide. The `options.functions` still works well.

**Comment by andyjansson** [comment]
>>    Loading PostCSS Plugin failed: Cannot find module './style/fn/xx.js'

Hi,

I don't think this error is originating from the plugin. Maybe there's something else going on?

**Comment by dtvn** [comment]
I can assure this is not missing file problem. I use a second option by `require()` the xx.js to a var and add it to `functions`. It works well.

Why do you think it is not plugin problem?

**Comment by andyjansson** [comment]
>Why do you think it is not plugin problem?

On account of the error message itself. There's nothing related to PostCSS when loading functions via `glob`. It's simply a `require`. That's why I suspect there might be something else going on here.

**Comment by dtvn** [comment]
Is there anyway for me to debug and get more info about this problem?

**Comment by andyjansson** [comment]
Sure. You could always set up a breakpoint around https://github.com/andyjansson/postcss-functions/blob/master/src/index.js#L19 to see what actually happens on your end.
