### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by thalesagapito** [andyjansson/postcss-functions#39]
Apparently even though the repo is using Postcss 8, the npm package is not updated. What is needed to update the npm package? Can I help out in some way?

**Comment by andyjansson** [comment]
Hi! Work is still being done on the plugin. Just hang in there a little bit longer.

**Comment by thalesagapito** [comment]
Okay, thanks for your work!

**Comment by andyjansson** [comment]
New version published.
