### ISSUE TITLE
Recommend version bump

### ISSUE THREAD

**Issue by stephenway** [andyjansson/postcss-functions#5]
Just installing this project doesn't pull the latest code with `walkDecls`. This produces a warning, so I've been installing on master instead. Just to clean up output, I'd like to recommend version bumping to 1.0.1 with a new git tag and npm publish.

**Comment by andyjansson** [comment]
Yep, it's coming. I just haven't gotten around to it yet.

**Comment by andyjansson** [comment]
V2 released.
