### ISSUE TITLE
Updating returned values from functions?

### ISSUE THREAD

**Issue by zellwk** [andyjansson/postcss-functions#55]
Hi! 

I'm using PostCSS functions with Astro (thus using Vite underneath the hood).

What I discovered is that PostCSS functions doesn't seem to update the returned value when we change the `postcss.config.js` file. 

```

module.exports = {
  plugins: [
    require('postcss-functions')({
      functions: {
        test: function () {
          return 'blue' // When I change this from blue to red, the values doesn't get hot reloaded. 
        },
      },
    }),
  ],
}

```

Is supporting this hot-reloading possible within postcss-functions? If not, can you point me in the right direction on how to set up something like this?

Thank you!

**Comment by andyjansson** [comment]
Hi,

Unfortunately there's nothing I can do from postcss-functions. This is likely something you need to investigate in your build script. Perhaps the fine folks in the [PostCSS Gitter chat](https://gitter.im/postcss/postcss) can steer you in the right direction?

**Comment by zellwk** [comment]
Thank you.
